[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5", features = ["std"] }
axum = {version = "0.8", features = ["macros"] }
axum-extra = { version = "0.12.5", features = ["typed-header"] }
base64 = "0.22.1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10.4"
color-eyre = "0.6"
dotenvy = "0.15"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
rand_core = "0.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = [
    "chrono",
    "uuid",
    "sqlite",
    "runtime-tokio",
] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.8", features = ["cors"] }
uuid = { version = "1", features = ["v7", "serde"] }
webauthn-rs = { version = "0.5.4", features = [
    "danger-allow-state-serialisation",
] }
web-push = "0.10"
tokio-cron-scheduler = "0.13"
openssl = { version = "0.10", features = ["vendored"] }
